'use client';
import { useMemo,useState } from 'react';
import { ChevronLeft,ChevronRight,Download,Plus,Clock3,LockKeyhole,Pencil,ExternalLink,CalendarDays } from 'lucide-react';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Switch } from '@/components/ui/switch';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Empty,EmptyTitle,EmptyDescription } from '@/components/ui/empty';
import { addDays,calendarICS,countdownTargetLabel,dateLabel,occursOn,todayISO,validDate,type CalendarEvent,type Countdown } from '@/lib/domain';
import { CountdownClock } from '@/components/countdown-clock';
import type { useHubData } from '@/lib/use-hub';
import official from '@/lib/official-calendar.json';
type State=ReturnType<typeof useHubData>;
type CalendarSource={name:string;url:string;message:string;references?:{name:string;url:string;status:string}[]};
export function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:(string|{value:string;label:string})[]}) {const values=options.map(o=>typeof o==='string'?{value:o,label:o}:o);return <label className="field"><span>{label}</span><Select value={value} onValueChange={v=>v!==null&&onChange(v)}><SelectTrigger className="control"><SelectValue>{values.find(o=>o.value===value)?.label||value}</SelectValue></SelectTrigger><SelectContent>{values.map(o=><SelectItem value={o.value} key={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></label>;}
export function Toggle({label,detail,checked,onChange}:{label:string;detail?:string;checked:boolean;onChange:(v:boolean)=>void}) {return <label className="toggle-row"><span>{label}{detail&&<small>{detail}</small>}</span><Switch checked={checked} onCheckedChange={onChange}/></label>;}
export function EmptyState({title,description}:{title:string;description:string}){return <Empty className="empty-state"><CalendarDays size={24}/><EmptyTitle>{title}</EmptyTitle><EmptyDescription>{description}</EmptyDescription></Empty>;}
export function CountdownCard({c,events,onEdit}:{c:Countdown;events:CalendarEvent[];onEdit:()=>void}){
 return <article className="countdown-card"><div className="row-between"><span className="tag"><LockKeyhole size={12}/> PRIVATE</span><button aria-label={'Edit '+c.title} className="icon-button" onClick={onEdit}><Pencil size={15}/></button></div><h3>{c.title}</h3><CountdownClock countdown={c} events={events}/><p>{countdownTargetLabel(c)}</p><small>{c.includeWeekends?'Weekends included':'Weekdays only'} · {c.includeHolidays?'Holidays included':'Holidays excluded'} · {c.includeDaysOff?'Days off included':'Days off excluded'}</small>{!c.includeDaysOff&&c.date>official.coverageEnd&&<p className="notice compact">School dates after {dateLabel(official.coverageEnd)} are not verified yet.</p>}</article>;
}
export function CalendarPage({state,events}:{state:State;events:CalendarEvent[]}){
 const today=todayISO(),[month,setMonth]=useState(today.slice(0,7)+'-01'),[selected,setSelected]=useState(today),[editingEvent,setEditingEvent]=useState<CalendarEvent|null>(null),[editingCountdown,setEditingCountdown]=useState<Countdown|null>(null),[message,setMessage]=useState('');
 const visible=events.filter(e=>state.plan.visibleKinds.includes(e.kind));
 const days=useMemo(()=>{const start=new Date(month+'T12:00:00Z').getUTCDay();return Array.from({length:42},(_,i)=>addDays(month,i-start));},[month]);
 const selectedEvents=visible.filter(e=>occursOn(e,selected));
 const changeMonth=(n:number)=>{const d=new Date(month+'T12:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,10));};
 async function filter(kind:string,on:boolean){try{await state.savePlan(current=>({...current,visibleKinds:on?[...current.visibleKinds,kind]:current.visibleKinds.filter(k=>k!==kind)}));}catch(e){setMessage((e as Error).message);}}
 function download(){const url=URL.createObjectURL(new Blob([calendarICS(visible)],{type:'text/calendar'}));const a=document.createElement('a');a.href=url;a.download='ib-info-calendar.ics';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 return <><div className="page-heading"><div><p className="eyebrow">PLAN YOUR DAYS</p><h1>Your calendar.</h1><p className="muted">Official dates, shared deadlines, and a little room for your own plans.</p></div><div className="inline-actions"><button onClick={download} className="button secondary"><Download size={17}/> Export</button><button disabled={!state.ready} className="button" onClick={()=>setEditingEvent({id:crypto.randomUUID(),title:'',date:selected,kind:'personal'})}><Plus size={17}/> Personal event</button></div></div>
 <p className="privacy-caption"><LockKeyhole size={14}/>{state.user?'Personal events and countdowns are saved privately to your account.':'Personal events and countdowns are saved on this browser. Sign in to save across devices.'}</p>
 {message&&<p role="status" className="notice">{message}</p>}
 <div className="calendar-layout"><section className="panel calendar-panel"><div className="calendar-toolbar"><h2>{dateLabel(month,{month:'long',year:'numeric'})}</h2><div className="inline-actions"><button className="button secondary small" onClick={()=>{setMonth(today.slice(0,7)+'-01');setSelected(today);}}>Today</button><button aria-label="Previous month" className="icon-button" onClick={()=>changeMonth(-1)}><ChevronLeft size={18}/></button><button aria-label="Next month" className="icon-button" onClick={()=>changeMonth(1)}><ChevronRight size={18}/></button></div></div><div className="calendar-grid" role="group" aria-label="Month calendar">{['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].map(d=><div className="weekday" key={d}>{d}</div>)}{days.map(d=>{const entries=visible.filter(e=>occursOn(e,d));return <button key={d} aria-pressed={selected===d} aria-label={dateLabel(d)+', '+entries.length+' events'} onClick={()=>setSelected(d)} className={['calendar-day',d.slice(0,7)!==month.slice(0,7)?'other-month':'',d===today?'today':'',d===selected?'selected':''].join(' ')}><span>{Number(d.slice(-2))}</span>{entries.slice(0,2).map(e=><span key={e.id} className={'calendar-entry '+e.kind}>{e.title}</span>)}{entries.length>2&&<small>+{entries.length-2} more</small>}</button>;})}</div></section>
 <aside className="calendar-aside"><section className="panel"><p className="eyebrow">ON THIS DAY</p><h2>{dateLabel(selected,{weekday:'short',month:'short',day:'numeric'})}</h2>{selectedEvents.length?selectedEvents.map(e=><article className="agenda-entry" key={e.id}><span className="tag">{e.kind==='personal'?'PRIVATE':e.kind.replace('-',' ')}</span><h3>{e.title}</h3>{e.note&&<p>{e.note}</p>}{e.endDate&&<small>Through {dateLabel(e.endDate)}</small>}{e.source&&<a href={e.source} target="_blank" rel="noreferrer" className="text-link">View source <ExternalLink size={13}/></a>}{state.plan.events.some(p=>p.id===e.id)&&<button className="text-link" onClick={()=>setEditingEvent(e)}>Edit personal event</button>}</article>):<p className="muted space-top">Nothing scheduled. A little breathing room.</p>}</section><section className="panel filter-panel"><h3>Show on my calendar</h3>{[['exam','IB exams'],['deadline','Shared deadlines'],['holiday','Holidays'],['day-off','School days off'],['personal','Personal events']].map(([kind,label])=><Toggle key={kind} label={label} checked={state.plan.visibleKinds.includes(kind)} onChange={on=>void filter(kind,on)}/>)}</section></aside></div>
 <div className="section-heading spacious" id="countdowns"><div><p className="eyebrow">LOOKING AHEAD</p><h2>Your countdowns</h2></div><button className="button secondary" disabled={!state.ready} onClick={()=>setEditingCountdown({id:crypto.randomUUID(),title:'',date:addDays(today,30),includeWeekends:true,includeHolidays:true,includeDaysOff:true,extraDaysOff:[]})}><Plus size={16}/> Add countdown</button></div>
 {state.plan.countdowns.length?<div className="core-grid">{state.plan.countdowns.map(c=><CountdownCard key={c.id} c={c} events={events} onEdit={()=>setEditingCountdown(c)}/>)}</div>:<EmptyState title="What are you working toward?" description="An exam, your EE draft, graduation, or your next day off. Give it a date and make it yours."/>}
 <section className="panel source-panel"><h3>Where the dates come from</h3>{(official.sources as CalendarSource[]).map(s=><div key={s.name}>{s.url?<a className="text-link" target="_blank" rel="noreferrer" href={s.url}>{s.name}<ExternalLink size={14}/></a>:<strong>{s.name}</strong>}<p>{s.message}</p>{s.references?.length?<p className="source-references">Copies checked: {s.references.map((reference,index)=><span key={reference.name}>{index>0?' · ':''}<a target="_blank" rel="noreferrer" href={reference.url}>{reference.name}</a>{reference.status==='agrees'?' ✓':''}</span>)}</p>:null}</div>)}<p className="muted">School calendar: {official.schoolYear}. Last successful check: {dateLabel(official.checkedAt.slice(0,10))}. Confirm official deadlines with your teacher or IB coordinator.</p></section>
 <Dialog open={!!editingEvent} onOpenChange={open=>!open&&setEditingEvent(null)}><DialogContent className="app-dialog"><DialogTitle>Personal event</DialogTitle><DialogDescription>Only your personal calendar changes.</DialogDescription>{editingEvent&&<EventForm key={editingEvent.id} event={editingEvent} existing={state.plan.events.some(e=>e.id===editingEvent.id)} onSave={async(e)=>{await state.savePlan(current=>({...current,events:[...current.events.filter(p=>p.id!==e.id),e]}));setEditingEvent(null);}} onDelete={async()=>{await state.savePlan(current=>({...current,events:current.events.filter(e=>e.id!==editingEvent.id)}));setEditingEvent(null);}}/>}</DialogContent></Dialog>
 <Dialog open={!!editingCountdown} onOpenChange={open=>!open&&setEditingCountdown(null)}><DialogContent className="app-dialog"><DialogTitle>Your countdown</DialogTitle><DialogDescription>Counts the included time remaining until your target, in Eastern time. Pauses on excluded days. Each displayed day is 24 included hours.</DialogDescription>{editingCountdown&&<CountdownForm key={editingCountdown.id} initial={editingCountdown} events={events} existing={state.plan.countdowns.some(c=>c.id===editingCountdown.id)} onSave={async(c)=>{await state.savePlan(current=>({...current,countdowns:[...current.countdowns.filter(p=>p.id!==c.id),c]}));setEditingCountdown(null);}} onDelete={async()=>{await state.savePlan(current=>({...current,countdowns:current.countdowns.filter(c=>c.id!==editingCountdown.id)}));setEditingCountdown(null);}}/>}</DialogContent></Dialog>
 </>;
}
function EventForm({event,existing,onSave,onDelete}:{event:CalendarEvent;existing:boolean;onSave:(e:CalendarEvent)=>Promise<void>;onDelete:()=>Promise<void>}){
 const [e,setE]=useState(event),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(action:()=>Promise<void>){setBusy(true);try{if(!validDate(e.date)||e.endDate&&(!validDate(e.endDate)||e.endDate<e.date))throw new Error('Choose a valid date range.');await action();}catch(err){setError((err as Error).message);}finally{setBusy(false);}}
 return <form className="form-stack" onSubmit={ev=>{ev.preventDefault();void run(()=>onSave(e));}}><label className="field">Title<Input required maxLength={120} value={e.title} onChange={ev=>setE({...e,title:ev.target.value})}/></label><div className="form-columns"><label className="field">Date<Input required type="date" value={e.date} onChange={ev=>setE({...e,date:ev.target.value})}/></label><label className="field">End date (optional)<Input type="date" min={e.date} value={e.endDate||''} onChange={ev=>setE({...e,endDate:ev.target.value||undefined})}/></label></div><label className="field">Notes<Textarea maxLength={2000} value={e.note||''} onChange={ev=>setE({...e,note:ev.target.value})}/></label>{error&&<p className="error-text" role="alert">{error}</p>}<div className="inline-actions"><button className="button" disabled={busy}>{busy?'Saving…':'Save event'}</button>{existing&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void run(onDelete)}>Remove event</button>}</div></form>;
}
function CountdownForm({initial,events,existing,onSave,onDelete}:{initial:Countdown;events:CalendarEvent[];existing:boolean;onSave:(c:Countdown)=>Promise<void>;onDelete:()=>Promise<void>}){
 const [c,setC]=useState(initial),[extras,setExtras]=useState(initial.extraDaysOff.join(', ')),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function run(action:()=>Promise<void>){setBusy(true);try{await action();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <form className="form-stack" onSubmit={e=>{e.preventDefault();void run(()=>onSave({...c,extraDaysOff:extras.split(/[\s,]+/).filter(Boolean)}));}}>
  <Choice label="Start from an event (optional)" value="custom" onChange={id=>{const e=events.find(e=>e.id===id);if(e)setC({...c,title:e.title,date:e.date});}} options={[{value:'custom',label:'Choose an event or enter your own'},...events.filter(e=>e.date>=todayISO()).map(e=>({value:e.id,label:e.title+' · '+dateLabel(e.date)}))]}/>
  <label className="field">Name<Input required maxLength={100} value={c.title} onChange={e=>setC({...c,title:e.target.value})}/></label>
  <div className="form-columns">
   <label className="field">Target date<Input required type="date" min="2000-01-01" max="2100-12-31" value={c.date} onChange={e=>setC({...c,date:e.target.value})}/></label>
   <label className="field">Target time (Eastern)<Input required type="time" value={c.time??'00:00'} onChange={e=>setC({...c,time:e.target.value})}/><small>12:00 AM is the start of the selected date. Existing countdowns default to that time.</small></label>
  </div>
  <div className="settings-box"><Toggle label="Include weekends" checked={c.includeWeekends} onChange={v=>setC({...c,includeWeekends:v})}/><Toggle label="Include official holidays" checked={c.includeHolidays} onChange={v=>setC({...c,includeHolidays:v})}/><Toggle label="Include other days off" detail="School breaks and your extra days below" checked={c.includeDaysOff} onChange={v=>setC({...c,includeDaysOff:v})}/></div>
  <label className="field">Extra days off<Textarea placeholder="2026-10-09, 2026-10-12" value={extras} onChange={e=>setExtras(e.target.value)}/><small>Separate dates with commas. Use YYYY-MM-DD.</small></label>
  {error&&<p className="error-text" role="alert">{error}</p>}<div className="inline-actions"><button className="button" disabled={busy}>{busy?'Saving…':'Save countdown'}</button>{existing&&<button type="button" className="button secondary" disabled={busy} onClick={()=>void run(onDelete)}>Remove countdown</button>}</div>
 </form>;
}
