'use client';
import { useEffect,useState } from 'react';
import { Check,ExternalLink,ShieldCheck,X } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { supabase } from '@/lib/supabase';
import { dateLabel,safeUrl,type HubItem } from '@/lib/domain';
import { EmptyState } from '@/components/calendar-page';
import type { State } from '@/components/workspace-content';
type Report={id:string;content_id:string;reason:string;status:string;created_at:string};
export function AdminPage({state}:{state:State}){
 const [queue,setQueue]=useState<HubItem[]>([]),[reports,setReports]=useState<Report[]>([]),[admins,setAdmins]=useState<{user_id:string;email:string}[]>([]),[adminEmail,setAdminEmail]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[tab,setTab]=useState('review'),[identity,setIdentity]=useState<{user_id:string;email:string}|null>(null),[moderation,setModeration]=useState('');
 const isAdmin=state.role==='owner'||state.role==='admin',isOwner=state.role==='owner';
 async function reload(){
  if(!supabase||!isAdmin)return;
  const q=await supabase.from('content').select('*').eq('status','pending').order('created_at');if(q.error)throw q.error;setQueue(q.data||[]);
  if(isOwner){const [r,a]=await Promise.all([supabase.from('reports').select('*').eq('status','open').order('created_at'),supabase.rpc('owner_admins')]);if(r.error||a.error)throw r.error||a.error;setReports(r.data||[]);setAdmins(a.data||[]);}
 }
 useEffect(()=>{void reload().catch(e=>setMessage(e.message));},[state.role]);
 async function run(action:()=>Promise<void>){setBusy(true);setMessage('');try{await action();await reload();await state.refresh();setMessage('Saved.');}catch(e){setMessage((e as Error).message);}finally{setBusy(false);}}
 async function rpc(name:string,p:Record<string,unknown>){const {data,error}=await supabase!.rpc(name,p);if(error)throw error;return data;}
 if(!state.user)return <EmptyState title="Sign in to manage the site" description="This space is available to the owner and approved admins."/>;
 if(!isAdmin)return <EmptyState title="Student account" description="The owner can add you as an admin. Only approved admins can review shared submissions."/>;
 return <><div className="page-heading"><div><p className="eyebrow">{isOwner?'OWNER WORKSPACE':'ADMIN WORKSPACE'}</p><h1>Keep the hub useful.</h1><p className="muted">Review contributions and moderate public content.</p></div><ShieldCheck size={32}/></div>{message&&<p className="notice" role="status">{message}</p>}<Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList className="category-tabs"><TabsTrigger value="review">Review queue ({queue.length})</TabsTrigger><TabsTrigger value="moderate">Published content</TabsTrigger>{isOwner&&<><TabsTrigger value="reports">Reports ({reports.length})</TabsTrigger><TabsTrigger value="admins">Admins</TabsTrigger></>}</TabsList><TabsContent value="review">{queue.length?queue.map(i=><article className="panel review-item" key={i.id}><div className="row-between"><span className="tag">{i.kind}</span><small>{dateLabel(i.created_at.slice(0,10))}</small></div><h2 className="space-top">{i.title}</h2><p>{i.subject} · {i.display_name}</p><p className="preserve-text space-top">{i.body}</p>{i.event_date&&<p className="space-top">Date: {dateLabel(i.event_date)}{i.end_date?' – '+dateLabel(i.end_date):''}</p>}{safeUrl(i.url)&&<a className="text-link space-top" href={safeUrl(i.url)} target="_blank" rel="noreferrer">Open submitted source <ExternalLink size={14}/></a>}{i.target_id&&<p className="notice">Approving this correction updates the original shared item. Original: {state.items.find(t=>t.id===i.target_id)?.title||i.target_id}</p>}<div className="inline-actions space-top"><button className="button" disabled={busy} onClick={()=>void run(()=>rpc('review_content',{item_id:i.id,decision:'approved'}))}><Check size={16}/> Approve</button><button className="button secondary" disabled={busy} onClick={()=>void run(()=>rpc('review_content',{item_id:i.id,decision:'rejected'}))}><X size={16}/> Reject</button>{isOwner&&<button className="text-link" onClick={()=>void run(async()=>setIdentity(await rpc('owner_identity',{item_id:i.id})))}>Owner identity lookup</button>}</div></article>):<EmptyState title="All caught up" description="New resources, dates, and corrections will appear here for review."/>}</TabsContent>
 <TabsContent value="moderate"><label className="field space-top">Find a contribution<Input placeholder="Search published content" value={moderation} onChange={e=>setModeration(e.target.value)}/></label>{state.items.filter(i=>[i.title,i.body].join(' ').toLowerCase().includes(moderation.toLowerCase())).map(i=><article className="panel review-item" key={i.id}><span className="tag">{i.kind}</span><h3>{i.title}</h3><p className="preserve-text">{i.body}</p><div className="inline-actions space-top"><button className="button secondary" disabled={busy} onClick={()=>void run(()=>rpc('review_content',{item_id:i.id,decision:'hidden'}))}>Hide from public view</button>{isOwner&&<button className="text-link" onClick={()=>void run(async()=>setIdentity(await rpc('owner_identity',{item_id:i.id})))}>Owner identity lookup</button>}</div></article>)}</TabsContent>
 {isOwner&&<><TabsContent value="reports">{reports.length?reports.map(r=><article className="panel review-item" key={r.id}><span className="tag">OWNER ONLY</span><h3>{state.items.find(i=>i.id===r.content_id)?.title||'Reported contribution'}</h3><p className="preserve-text">{r.reason}</p><div className="inline-actions space-top"><button disabled={busy} className="button" onClick={()=>void run(()=>rpc('owner_resolve_report',{report_id:r.id}))}>Mark resolved</button><button disabled={busy} className="button secondary" onClick={()=>void run(()=>rpc('review_content',{item_id:r.content_id,decision:'hidden'}))}>Hide contribution</button><button disabled={busy} className="button secondary" onClick={()=>void run(()=>rpc('owner_ban_author',{item_id:r.content_id,ban_reason:r.reason}))}>Restrict author’s posting</button><button className="text-link" onClick={()=>void run(async()=>setIdentity(await rpc('owner_identity',{item_id:r.content_id})))}>Look up author</button></div></article>):<EmptyState title="No open reports" description="Only you can read reports submitted by students."/>}</TabsContent>
 <TabsContent value="admins"><section className="panel space-top"><h2>Additional admins</h2><p className="muted space-top">Admins can approve submissions and hide content. They cannot read reports, look up anonymous authors, or access personal plans.</p><form className="form-stack space-top" onSubmit={e=>{e.preventDefault();void run(async()=>{await rpc('owner_set_admin',{member_email:adminEmail,make_admin:true});setAdminEmail('');});}}><label className="field">Student account email<Input required type="email" value={adminEmail} onChange={e=>setAdminEmail(e.target.value)}/><small>They need to sign in to IB Info once before you can add them.</small></label><button disabled={busy} className="button">Add admin</button></form>{admins.map(a=><div key={a.user_id} className="row-between agenda-entry"><p>{a.email}</p><button className="text-link" disabled={busy} onClick={()=>void run(()=>rpc('owner_set_admin',{member_email:a.email,make_admin:false}))}>Remove admin access</button></div>)}</section></TabsContent></>}
 </Tabs><Dialog open={!!identity} onOpenChange={open=>!open&&setIdentity(null)}><DialogContent className="app-dialog"><DialogTitle>Owner-only identity lookup</DialogTitle><DialogDescription>This access is logged. Additional admins cannot use this lookup.</DialogDescription><p>{identity?.email}</p><p className="muted break-all">Account: {identity?.user_id}</p></DialogContent></Dialog></>;
}
