'use client';
import { useEffect,useState } from 'react';
import Link from '@/components/site-link';
import { ArrowUpRight,BookOpen,Clock3,ExternalLink,Flag,LockKeyhole,MessageCircle,Plus,Search,ShieldCheck,Star } from 'lucide-react';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Checkbox } from '@/components/ui/checkbox';
import { Dialog,DialogContent,DialogTitle,DialogDescription } from '@/components/ui/dialog';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { CalendarPage,Choice,EmptyState,Toggle } from '@/components/calendar-page';
import { AdminPage } from '@/components/management-pages';
import { AccountPage } from '@/components/account-page';
import { categories,core,officialResources,starterTips,subjectGroups,subjects } from '@/lib/catalog';
import { connected,supabase } from '@/lib/supabase';
import { dateLabel,countdownTargetLabel,safeUrl,todayISO,toEvent,type CalendarEvent,type HubItem, type ItemKind } from '@/lib/domain';
import { CountdownClock } from '@/components/countdown-clock';
import { useHubData } from '@/lib/use-hub';
import official from '@/lib/official-calendar.json';
export type State=ReturnType<typeof useHubData>;
export const pageTitles:Record<string,string>={home:'Overview',calendar:'Calendar',subjects:'Subjects',ee:'Extended essay',tok:'Theory of knowledge',cas:'Creativity, activity, service','study-tips':'Study tips',resources:'Resources',forum:'Forum',submit:'Submit',account:'Your account',admin:'Administration',privacy:'Community & privacy'};
export function WorkspaceContent({section,state}:{section:string;state:State}){
 const [officialEvents,setOfficialEvents]=useState<CalendarEvent[]>(official.events as CalendarEvent[]);
 useEffect(()=>{const context=(document as Document & {modelContext?:{registerTool:(tool:unknown,options?:unknown)=>Promise<void>}}).modelContext;if(!context)return;const lifecycle=new AbortController();void Promise.resolve(context.registerTool({name:'read_calendar',title:'Read calendar',description:'Read public calendar dates currently displayed in IB Info. Personal plans are excluded.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:(input:unknown)=>{if(!input||typeof input!=='object'||Object.keys(input).length)throw new Error('Provide an empty object.');return {events:officialEvents,schoolYear:official.schoolYear};}},{signal:lifecycle.signal})).catch(()=>{});return()=>lifecycle.abort();},[officialEvents]);
 const events=[...officialEvents,...state.items.map(toEvent).filter((e):e is CalendarEvent=>!!e),...state.plan.events];
 let page;
 if(section==='calendar')page=<CalendarPage state={state} events={events}/>;
 else if(section==='subjects')page=<SubjectsPage state={state}/>;
 else if(section in core)page=<CorePage section={section as keyof typeof core} state={state}/>;
 else if(section==='resources')page=<ResourcesPage state={state}/>;
 else if(section==='study-tips')page=<TipsPage state={state}/>;
 else if(section==='forum')page=<ForumPage state={state}/>;
 else if(section==='submit')page=<SubmitPage state={state}/>;
 else if(section==='account')page=<AccountPage state={state}/>;
 else if(section==='admin')page=<AdminPage state={state}/>;
 else if(section==='privacy')page=<PrivacyPage/>;
 else page=<Overview state={state} events={events}/>;
 return <>{!connected&&<div className="preview-note">Preview · Personal planning works on this browser. Community posting and accounts are awaiting connection.</div>}{state.error&&<p role="alert" className="notice error-text">{state.error}<button className="text-link" onClick={()=>{state.setError('');void state.refresh();}}>Try again</button></p>}{page}</>;
}
function PageHeading({eyebrow,title,description,action}:{eyebrow:string;title:string;description:string;action?:React.ReactNode}){return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p className="muted">{description}</p></div>{action}</div>;}
function Contribute({type='resource',subject='General',label='Contribute'}:{type?:string;subject?:string;label?:string}){return <Link className="button" href={'/submit/?type='+encodeURIComponent(type)+'&subject='+encodeURIComponent(subject)}><Plus size={17}/>{label}</Link>;}
function Overview({state,events}:{state:State;events:CalendarEvent[]}){
 const upcoming=events.filter(e=>(e.endDate||e.date)>=todayISO()).sort((a,b)=>a.date.localeCompare(b.date)).slice(0,3),countdown=state.plan.countdowns[0];
 return <><PageHeading eyebrow="YOUR STUDENT WORKSPACE" title="Your IB, in one place." description="Keep the next deadline in sight. Find what you need. Help each other out." action={<Contribute/>}/>
 <div className="dashboard-grid"><section className="countdown-feature"><div className="row-between"><span className="eyebrow">{countdown?'YOUR PRIVATE COUNTDOWN':'MAKE ROOM FOR WHAT’S NEXT'}</span><Clock3 size={22}/></div>{countdown?<><h2>{countdown.title}</h2><CountdownClock countdown={countdown} events={events} featured/><p>{countdownTargetLabel(countdown)} · With your counting settings</p><Link href="/calendar/#countdowns" className="button gold">Manage countdowns <ArrowUpRight size={17}/></Link></>:<><h2>A countdown that<br/>works on your time.</h2><p>Count every day, or just your school days.<br/>Your goals stay private.</p><Link href="/calendar/#countdowns" className="button gold"><Plus size={17}/> Create a countdown</Link></>}<div className="feature-footer">WEEKENDS · HOLIDAYS · YOUR DAYS OFF</div></section><section className="panel upcoming-panel"><div className="section-heading"><h2>Coming up</h2><Link href="/calendar/">Full calendar <ArrowUpRight size={16}/></Link></div>{upcoming.length?upcoming.map(e=><div className="date-row" key={e.id}><span className="date-tile">{dateLabel(e.date,{month:'short'}).toUpperCase()}<strong>{e.date.slice(-2)}</strong></span><div><span className="tag">{e.kind.replace('-',' ').toUpperCase()}</span><h3>{e.title}</h3><p>{e.official?(e.id.startsWith('ib-')?'International Baccalaureate':'Official school calendar'):e.kind==='personal'?'Your private calendar':'Community-approved'}</p></div></div>):<EmptyState title="No upcoming dates" description="Add a personal event or submit a shared deadline."/>}<p className="source-line"><ShieldCheck size={15}/> Official sources and approved contributions</p></section></div>
 <div className="section-heading spacious"><div><p className="eyebrow">THE DIPLOMA CORE</p><h2>Three big pieces. One place to start.</h2></div></div><div className="core-grid">{Object.entries(core).map(([id,c])=><Link href={'/'+id+'/'} className="core-card" key={id}><div className="row-between"><span className="core-monogram">{c.short}</span><ArrowUpRight size={20}/></div><h3>{c.title}</h3><p>{c.intro}</p><small>Guidance, shared resources & conversation</small></Link>)}</div>
 <div className="two-col spacious"><section className="panel"><div className="section-heading"><h2>Your subjects</h2><Link href="/subjects/">Choose subjects <ArrowUpRight size={16}/></Link></div>{state.plan.subjects.length?<div className="pill-list">{state.plan.subjects.map(s=><Link key={s} href={'/resources/?subject='+encodeURIComponent(s)}>{s}</Link>)}</div>:<p className="muted">Choose your subjects to keep their resources close.</p>}</section><section className="panel"><div className="section-heading"><h2>From the community</h2><Link href="/forum/">Open forum <ArrowUpRight size={16}/></Link></div>{state.items.filter(i=>i.kind==='thread').slice(0,2).map(i=><p key={i.id} className="community-preview">{i.title}</p>)}{!state.items.some(i=>i.kind==='thread')&&<p className="muted">A place for the question someone else is probably wondering about too.</p>}</section></div></>;
}
function SubjectsPage({state}:{state:State}){
 const [q,setQ]=useState(''),[error,setError]=useState('');
 async function pin(name:string){try{await state.savePlan(current=>({...current,subjects:current.subjects.includes(name)?current.subjects.filter(s=>s!==name):[...current.subjects,name]}));}catch(e){setError((e as Error).message);}}
 const groups=subjectGroups.map(g=>({...g,subjects:g.subjects.filter(s=>s.toLowerCase().includes(q.toLowerCase()))})).filter(g=>g.subjects.length);
 return <><PageHeading eyebrow="EXPLORE THE DIPLOMA" title="Find your subjects." description="All six subject groups. Save yours for quick access."/><div className="search-box"><Search size={18}/><Input aria-label="Search subjects" placeholder="Search biology, history, mathematics…" value={q} onChange={e=>setQ(e.target.value)}/></div>{error&&<p role="alert" className="error-text">{error}</p>}{groups.map((g,i)=><section key={g.name} className="subject-group"><div className="section-heading"><h2><span className="group-number">{String(subjectGroups.indexOf(subjectGroups.find(s=>s.name===g.name)!)+1).padStart(2,'0')}</span>{g.name}</h2></div><div className="subject-grid">{g.subjects.map(s=><article className="subject-card" key={s}><BookOpen size={20}/><Link href={'/resources/?subject='+encodeURIComponent(s)}>{s}<small>Resources & contributions <ArrowUpRight size={12}/></small></Link><button disabled={!state.ready} aria-label={(state.plan.subjects.includes(s)?'Unsave ':'Save ')+s} aria-pressed={state.plan.subjects.includes(s)} className="icon-button" onClick={()=>void pin(s)}><Star size={16} fill={state.plan.subjects.includes(s)?'currentColor':'none'}/></button></article>)}</div></section>)}{!groups.length&&<EmptyState title="No matching subjects" description="Try a shorter search or a different subject name."/>}<p className="notice">Language courses support any language. For school-based or pilot subjects, use “Other / school-based” when contributing. Availability and levels vary by school. <a href="https://ibo.org/programmes/diploma-programme/curriculum/" target="_blank" rel="noreferrer" className="text-link">Official IB subject directory <ExternalLink size={14}/></a></p></>;
}
function CorePage({section,state}:{section:keyof typeof core;state:State}){const c=core[section];return <><PageHeading eyebrow={'THE DIPLOMA CORE · '+c.short} title={c.title+'.'} description={c.intro} action={<Contribute subject={c.short} label="Add a resource"/>}/><section className="core-intro panel"><span className="core-monogram">{c.short}</span><div><h2>{c.description}</h2><a className="text-link space-top" href={c.url} target="_blank" rel="noreferrer">Read the official IB overview <ExternalLink size={15}/></a></div></section><ResourcesPage state={state} embedded={c.short}/><div className="panel row-between spacious"><div><h3>Work through it together.</h3><p className="muted">Ask a question or share an approach in the {c.short} forum.</p></div><Link className="button secondary" href={'/forum/?category='+c.short}>Join the discussion <ArrowUpRight size={16}/></Link></div></>;}
function ResourcesPage({state,embedded}:{state:State;embedded?:string}){
 const [query,setQuery]=useState(''),[subject,setSubject]=useState(embedded||'All subjects');
 useEffect(()=>{if(!embedded){const s=new URLSearchParams(location.search).get('subject');if(s)setSubject(s);}},[embedded]);
 const resources=[...officialResources.map(r=>({...r,display_name:r.author,official:true})),...state.items.filter(i=>i.kind==='resource').map(i=>({...i,official:false}))].filter(r=>(subject==='All subjects'||r.subject===subject)&&[r.title,r.body,r.subject].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <>{!embedded&&<PageHeading eyebrow="THE SHARED LIBRARY" title="A good starting point." description="Official guidance and resources contributed by students, reviewed before publishing." action={<Contribute label="Add resource"/>}/>}<div className="filter-toolbar"><div className="search-box"><Search size={18}/><Input aria-label="Search resources" placeholder="Find a guide, link, or resource…" value={query} onChange={e=>setQuery(e.target.value)}/></div>{!embedded&&<Choice label="Subject" value={subject} onChange={setSubject} options={['All subjects','General','EE','TOK','CAS',...subjects,'Other / school-based']}/>}</div><div className="resource-grid">{resources.map(r=><article className="resource-card" key={r.id}><div className="row-between"><span className="tag">{r.subject}</span>{r.official?<ShieldCheck size={17}/>:<ReportButton itemId={r.id} state={state}/>}</div><h3>{r.title}</h3><p>{r.body}</p><div className="resource-footer"><small>{r.official?'Official source':r.display_name}</small><a className="text-link" href={safeUrl(r.url)||undefined} target="_blank" rel="noreferrer">Open resource <ArrowUpRight size={17}/></a></div>{!r.official&&<Link className="text-link correction-link" href={'/submit/?type=correction&target='+r.id}>Suggest a correction</Link>}</article>)}</div>{!resources.length&&<EmptyState title="Make this library yours" description="No resources match yet. Share a useful link for the admins to review."/>}</>;
}
function TipsPage({state}:{state:State}){
 const [q,setQ]=useState('');const tips=[...starterTips.map((t,i)=>({...t,id:'starter-'+i,display_name:'IB Info · starter tip',starter:true})),...state.items.filter(i=>i.kind==='tip').map(i=>({...i,starter:false}))].filter(t=>[t.title,t.body,t.subject].join(' ').toLowerCase().includes(q.toLowerCase()));
 return <><PageHeading eyebrow="LEARN FROM EACH OTHER" title="Little things that help." description="An open collection of student advice. Share what works for you." action={<Contribute type="tip" label="Share a tip"/>}/><div className="search-box"><Search size={18}/><Input aria-label="Search study tips" placeholder="Search study tips…" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="resource-grid spacious">{tips.map(t=><article className="resource-card" key={t.id}><div className="row-between"><span className="tag">{t.subject}</span>{!t.starter&&<ReportButton itemId={t.id} state={state}/>}</div><h3>{t.title}</h3><p className="preserve-text">{t.body}</p><small className="space-top muted">{t.display_name}</small></article>)}</div>{!tips.length&&<EmptyState title="No matching tips" description="Try another search or share a tip of your own."/>}</>;
}
function ForumPage({state}:{state:State}){
 const [category,setCategory]=useState('All'),[q,setQ]=useState(''),[thread,setThread]=useState<HubItem|null>(null);
 useEffect(()=>{const c=new URLSearchParams(location.search).get('category');if(c&&categories.includes(c))setCategory(c);},[]);
 const threads=state.items.filter(i=>i.kind==='thread'&&(category==='All'||i.category===category)&&[i.title,i.body].join(' ').toLowerCase().includes(q.toLowerCase()));
 return <><PageHeading eyebrow="THE COMMON ROOM" title="Ask. Share. Figure it out." description="Conversations for students, by students. Be respectful and keep personal information private." action={<Contribute type="thread" label="Start a discussion"/>}/><div className="search-box"><Search size={18}/><Input aria-label="Search discussions" placeholder="What’s on your mind?" value={q} onChange={e=>setQ(e.target.value)}/></div><Tabs value={category} onValueChange={v=>setCategory(String(v))} className="forum-tabs"><TabsList className="category-tabs" variant="line">{['All',...categories].map(c=><TabsTrigger key={c} value={c}>{c}</TabsTrigger>)}</TabsList><TabsContent value={category}>{threads.length?<div className="thread-list">{threads.map(t=><article className="thread-row" key={t.id}><MessageCircle size={22}/><button className="thread-title" onClick={()=>setThread(t)}><span className="tag">{t.category}</span><h3>{t.title}</h3><small>{t.display_name} · {dateLabel(t.created_at.slice(0,10))}</small></button><span className="reply-count">{state.items.filter(r=>r.parent_id===t.id&&r.kind==='reply').length} replies</span><ReportButton itemId={t.id} state={state}/></article>)}</div>:<EmptyState title="The conversation starts here" description="No discussions in this view yet. Ask a question or share something helpful."/>}</TabsContent></Tabs><p className="notice">No explicit language, racism, harassment, or personal attacks. Posts appear immediately and can be reported to the owner. <Link href="/privacy/" className="text-link">Community and privacy rules</Link></p><Dialog open={!!thread} onOpenChange={open=>!open&&setThread(null)}><DialogContent className="app-dialog wide"><DialogTitle>{thread?.title}</DialogTitle><DialogDescription>{thread?.category} · {thread?.display_name}</DialogDescription>{thread&&<ThreadDetail thread={thread} state={state}/>}</DialogContent></Dialog></>;
}
function ThreadDetail({thread,state}:{thread:HubItem;state:State}){
 const [reply,setReply]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState('');
 return <><p className="preserve-text">{thread.body}</p><div className="replies">{state.items.filter(r=>r.parent_id===thread.id&&r.kind==='reply').map(r=><article key={r.id}><div className="row-between"><small>{r.display_name}</small><ReportButton state={state} itemId={r.id}/></div><p className="preserve-text">{r.body}</p></article>)}</div>{state.user?<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{await state.submit({kind:'reply',title:'Reply',body:reply,parent_id:thread.id,category:thread.category,subject:thread.subject,display_name:'Anonymous'});setReply('');}catch(err){setError((err as Error).message);}finally{setBusy(false);}}}><label className="field">Your reply<Textarea required minLength={3} maxLength={10000} value={reply} onChange={e=>setReply(e.target.value)}/></label><small className="muted">Posts as Anonymous. The owner can identify your account; other students and admins cannot.</small>{error&&<p className="error-text" role="alert">{error}</p>}<button className="button" disabled={busy}>{busy?'Posting…':'Post reply'}</button></form>:<Link href="/account/" className="button secondary">Sign in to reply</Link>}</>;
}
export function ReportButton({itemId,state}:{itemId:string;state:State}){
 const [open,setOpen]=useState(false),[reason,setReason]=useState(''),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[sent,setSent]=useState(false);
 return <><button className="icon-button subtle" aria-label="Report this contribution" onClick={()=>{setOpen(true);setSent(false);setMessage('');}}><Flag size={15}/></button><Dialog open={open} onOpenChange={setOpen}><DialogContent className="app-dialog"><DialogTitle>Report to the owner</DialogTitle><DialogDescription>Your report is visible only to the site owner.</DialogDescription>{sent?<p role="status">{message}</p>:state.user?<form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);try{const {error}=await supabase!.rpc('report_content',{item_id:itemId,report_reason:reason});if(error)throw error;setSent(true);setMessage('Your report was sent to the owner.');setReason('');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}><label className="field">What should the owner know?<Textarea required minLength={3} maxLength={2000} value={reason} onChange={e=>setReason(e.target.value)}/></label>{message&&<p role="alert" className="error-text">{message}</p>}<button className="button" disabled={busy}>{busy?'Sending…':'Send report'}</button></form>:<Link href="/account/" className="button">Sign in to report</Link>}</DialogContent></Dialog></>;
}
function SubmitPage({state}:{state:State}){
 const [kind,setKind]=useState<ItemKind>('resource'),[title,setTitle]=useState(''),[body,setBody]=useState(''),[subject,setSubject]=useState('General'),[category,setCategory]=useState('General'),[url,setUrl]=useState(''),[date,setDate]=useState(''),[end,setEnd]=useState(''),[target,setTarget]=useState(''),[anonymous,setAnonymous]=useState(true),[nickname,setNickname]=useState(''),[agreed,setAgreed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[success,setSuccess]=useState(false),[myItems,setMyItems]=useState<HubItem[]>([]);
 useEffect(()=>{const p=new URLSearchParams(location.search),k=p.get('type');if(k&&['resource','deadline','event','correction','tip','thread'].includes(k))setKind(k as ItemKind);if(p.get('subject'))setSubject(p.get('subject')!);if(p.get('target'))setTarget(p.get('target')!);},[]);
 useEffect(()=>{const t=state.items.find(i=>i.id===target);if(t){setTitle(t.title);setBody(t.body);setSubject(t.subject);setUrl(t.url);setDate(t.event_date||'');setEnd(t.end_date||'');}},[target,state.items]);
 useEffect(()=>{if(state.user&&supabase)void supabase.rpc('my_submissions').then(({data})=>setMyItems(data||[]));},[state.user,success]);
 const immediate=['tip','thread'].includes(kind),dateNeeded=['deadline','event','correction'].includes(kind);
 return <><PageHeading eyebrow="BUILD THIS TOGETHER" title="Something worth sharing?" description="Add a useful link, flag a deadline, or pass along something that helped."/><div className="submit-layout"><section className="panel"><form className="form-stack" onSubmit={async e=>{e.preventDefault();setBusy(true);setSuccess(false);setMessage('');try{if(!agreed)throw new Error('Please agree to the community rules.');if(url&&!safeUrl(url))throw new Error('Use an http or https link.');await state.submit({kind,title,body,subject,category,url,event_date:dateNeeded?date:null,end_date:dateNeeded?end:null,target_id:kind==='correction'?target:null,display_name:anonymous?'Anonymous':nickname});setSuccess(true);setMessage(immediate?'Published. Thanks for contributing!':'Submitted to the admins for review.');setTitle('');setBody('');setUrl('');setDate('');setEnd('');}catch(err){setMessage((err as Error).message);}finally{setBusy(false);}}}>
 <Choice label="What would you like to share?" value={kind} onChange={v=>{setKind(v as ItemKind);setSuccess(false);setMessage('');}} options={['resource','deadline','event','tip','thread','correction'].map(value=>({value,label:({resource:'Resource',deadline:'Deadline',event:'Shared event',tip:'Study tip',thread:'Forum discussion',correction:'Correction to a shared item'})[value]!}))}/>
 {kind==='correction'&&<Choice label="Item to correct" value={target} onChange={setTarget} options={[{value:'',label:'Select the shared item'},...state.items.filter(i=>['resource','deadline','event'].includes(i.kind)).map(i=>({value:i.id,label:i.title}))]}/>}
 <label className="field">{kind==='correction'?'Corrected title':'Title'}<Input required maxLength={160} value={title} onChange={e=>setTitle(e.target.value)} placeholder={kind==='thread'?'Ask a clear, specific question':'Give it a clear name'}/></label><div className="form-columns"><Choice label="Subject / core" value={subject} onChange={setSubject} options={['General','EE','TOK','CAS',...subjects,'Other / school-based']}/>{kind==='thread'&&<Choice label="Forum category" value={category} onChange={setCategory} options={categories}/>}</div>
 {dateNeeded&&<div className="form-columns"><label className="field">Date<Input required={kind!=='correction'||!!date} type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="field">End date (optional)<Input type="date" min={date} value={end} onChange={e=>setEnd(e.target.value)}/></label></div>}
 <label className="field">{kind==='resource'?'Resource link':'Source link (optional)'}<Input required={kind==='resource'} type="url" placeholder="https://" value={url} onChange={e=>setUrl(e.target.value)} maxLength={2000}/></label>
 <label className="field">{kind==='correction'?'Corrected description and explanation':'Details'}<Textarea required minLength={3} maxLength={10000} rows={6} value={body} onChange={e=>setBody(e.target.value)} placeholder={kind==='deadline'?'What is due, and where was the date announced?':'Add context that will help another student.'}/></label><Toggle label="Show as Anonymous" detail="Only the owner can look up your account." checked={anonymous} onChange={setAnonymous}/>{!anonymous&&<label className="field">Public nickname<Input required maxLength={40} value={nickname} onChange={e=>setNickname(e.target.value)}/></label>}
 <label className="check-row"><Checkbox checked={agreed} onCheckedChange={v=>setAgreed(v===true)}/><span>I’ll be respectful, avoid explicit or hateful language, and share only material I’m allowed to share.</span></label>{message&&<p className={success?'success-text':'error-text'} role={success?'status':'alert'}>{message}</p>}{state.user?<button className="button" disabled={busy||!agreed}>{busy?'Sending…':immediate?'Publish contribution':'Send for review'}</button>:<Link href="/account/" className="button">Sign in to submit</Link>}</form></section><aside><section className="panel"><ShieldCheck size={26}/><h3 className="space-top">{immediate?'Your voice, in the conversation.':'A quick check before it goes live.'}</h3><p className="muted">{immediate?'Tips and discussions appear immediately. The owner and admins can moderate posts.':'Admins review shared resources, dates, events, and corrections. Your personal calendar does not need approval.'}</p><p className="notice compact">Official calendar imports keep their source dates. If an official date looks wrong, report the source to the owner.</p><Link href="/privacy/" className="text-link">Read the community rules</Link></section>{myItems.length>0&&<section className="panel space-top"><h3>Your recent submissions</h3>{myItems.slice(0,8).map(i=><div key={i.id} className="agenda-entry"><span className="tag">{i.status}</span><p>{i.title}</p></div>)}</section>}</aside></div></>;
}
function PrivacyPage(){return <><PageHeading eyebrow="A COMMUNITY WE CAN TRUST" title="Community & privacy." description="Clear expectations for everyone who uses IB Info."/><div className="prose-panel panel"><h2>Be respectful</h2><p>No explicit language, racism, discrimination, harassment, threats, or personal attacks. Avoid sharing other people’s personal information. Use the report button if something needs the owner’s attention.</p><h2>Anonymous to the community</h2><p>You sign in with an email account. When you post as Anonymous, your email and account identifier are hidden from visitors and additional site admins. The site owner can look up the account behind a contribution and review reports. This lookup is logged. Email verification is currently off, so an address entered at signup does not prove who owns the account. This is not an untraceable service; the hosting and sign-in providers also process operational data.</p><h2>Your personal plans</h2><p>Without sign-in, personal events, countdowns, and preferences stay in this browser. Anyone with access to this browser profile may access them, and clearing browser storage removes them. Signed-in plans are private to your account through the website. They are not visible to student admins or included in public calendar data. The infrastructure owner retains technical access to the database.</p><h2>Shared information</h2><p>Resources, deadlines, events, and corrections go through admin review. Study tips and discussions appear immediately, subject to moderation. Reports go only to the owner. Automated language filters help enforce the rules, but can miss harmful language or flag harmless text; the owner can review reports.</p><h2>Sources and ownership</h2><p>Link to original resources and credit their creators. Only contribute material you have permission to share. Student tips are community advice, not official IB guidance. This student-run site is independent of the IB and any school. Confirm official deadlines and exam arrangements with your teachers and coordinator.</p><h2>Corrections or removal</h2><p>Use the report form on a contribution to ask the owner for a correction or removal. Personal calendar entries and countdowns can be removed directly from your calendar.</p></div></>;}
