import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
const ids={owner:'11111111-1111-4111-8111-111111111111',admin:'22222222-2222-4222-8222-222222222222',student:'33333333-3333-4333-8333-333333333333',other:'44444444-4444-4444-8444-444444444444'};
test('Database permissions, approvals, identities and reports',async t=>{
 const db=new PGlite();await db.waitReady;
 await db.exec("create role anon;create role authenticated;create schema auth;create table auth.users(id uuid primary key,email text,email_confirmed_at timestamptz);create function auth.uid() returns uuid language sql stable as $$select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid$$;grant usage on schema auth to anon,authenticated;grant execute on function auth.uid() to anon,authenticated;");
 for(const [name,id]of Object.entries(ids))await db.query('insert into auth.users values($1,$2,now())',[id,name+'@example.test']);
 await db.exec(await readFile(new URL('../supabase/migrations/202609040001_ib_info.sql',import.meta.url),'utf8'));
 await db.query('select public.configure_owner($1)',['owner@example.test']);
 async function as(name){await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[ids[name]||'']);await db.exec(name==='anon'?'set role anon':'set role authenticated');}
 async function scalar(q,p=[]){return (await db.query(q,p)).rows[0];}
 async function rpc(name,p){return await scalar('select to_jsonb(public.'+name+'($1::jsonb)) as value',[JSON.stringify(p)]);}
 let pending,post,report;
 await t.test('First visitors cannot claim owner or self-promote',async()=>{await as('student');assert.equal((await scalar('select public.my_role() as role')).role,'student');await assert.rejects(db.query("select public.configure_owner('student@example.test')"),/permission denied/);await assert.rejects(db.query("select public.owner_set_admin('student@example.test',true)"),/Owner access/);});
 await t.test('Pending important content is not public',async()=>{await as('student');pending=(await rpc('submit_content',{kind:'deadline',title:'Draft deadline',body:'Teacher announcement',event_date:'2026-10-01',subject:'EE'})).value;assert.equal(pending.status,'pending');await as('anon');assert.equal((await db.query('select * from public.content')).rows.length,0);await assert.rejects(db.query("insert into public.content(kind,title,status) values('tip','Injected','approved')"),/permission denied/);});
 await t.test('Students cannot approve their own submissions',async()=>{await as('student');await assert.rejects(db.query("select public.review_content($1,'approved')",[pending.id]),/Administrator access/);});
 await t.test('Owner can add an admin who can approve without seeing identities',async()=>{await as('owner');await db.query("select public.owner_set_admin('admin@example.test',true)");await as('admin');assert.equal((await scalar('select public.my_role() as role')).role,'admin');await db.query("select public.review_content($1,'approved')",[pending.id]);await assert.rejects(db.query('select public.owner_identity($1)',[pending.id]),/Only the site owner/);await assert.rejects(db.query('select * from private.authorship'),/permission denied/);});
 await t.test('Public results contain no underlying author identifier',async()=>{await as('anon');const rows=(await db.query('select * from public.content')).rows;assert.equal(rows.length,1);assert.equal(rows[0].display_name,'Anonymous');assert.equal('user_id'in rows[0],false);assert.equal('email'in rows[0],false);});
 await t.test('Tips publish immediately while server filtering cannot be bypassed',async()=>{await as('student');post=(await rpc('submit_content',{kind:'tip',title:'Study in short sessions',body:'Try a focused session and a short break.'})).value;assert.equal(post.status,'approved');await assert.rejects(rpc('submit_content',{kind:'thread',title:'Test',body:'fuck this'}),/remove explicit/);await assert.rejects(rpc('submit_content',{kind:'resource',title:'Test',body:'Bad link',url:'javascript:alert(1)'}),/http or https/);});
 await t.test('Private plans cannot be read or overwritten by students or admins',async()=>{await as('student');await db.query('insert into public.personal_plans(user_id,data) values($1,$2)',[ids.student,JSON.stringify({countdowns:[{title:'Private target'}]})]);for(const role of ['other','admin','owner']){await as(role);assert.equal((await db.query('select * from public.personal_plans')).rows.length,0);await assert.rejects(db.query('insert into public.personal_plans(user_id,data) values($1,$2)',[ids.student,'{}']),/row-level security/);}await as('student');assert.equal((await db.query('select * from public.personal_plans')).rows.length,1);});
 await t.test('Reports go only to owner, not other admins',async()=>{await as('other');await db.query('select public.report_content($1,$2)',[post.id,'Please review this advice']);await as('admin');assert.equal((await db.query('select * from public.reports')).rows.length,0);await as('owner');report=(await db.query('select * from public.reports')).rows[0];assert.ok(report);const identity=(await scalar('select public.owner_identity($1) as identity',[post.id])).identity;assert.equal(identity.email,'student@example.test');await db.query('select public.owner_resolve_report($1)',[report.id]);assert.equal((await scalar('select status from public.reports where id=$1',[report.id])).status,'resolved');});
 await t.test('Approved correction updates its target; rejected corrections do not',async()=>{await as('student');const c=(await rpc('submit_content',{kind:'correction',title:'Updated draft deadline',body:'Date corrected',target_id:pending.id,event_date:'2026-10-02'})).value;await as('admin');await db.query("select public.review_content($1,'approved')",[c.id]);assert.equal((await scalar('select event_date::text as day from public.content where id=$1',[pending.id])).day,'2026-10-02');await assert.rejects(db.query("select public.review_content($1,'approved')",[c.id]),/already reviewed/);});
 await t.test('Rejected corrections leave the shared deadline unchanged',async()=>{await as('student');const correction=(await rpc('submit_content',{kind:'correction',title:'Unverified change',body:'Not approved',target_id:pending.id,event_date:'2026-10-10'})).value;await as('admin');await db.query("select public.review_content($1,'rejected')",[correction.id]);assert.equal((await scalar('select event_date::text as day from public.content where id=$1',[pending.id])).day,'2026-10-02');});
 await t.test('Hiding a thread hides its replies and prevents new replies',async()=>{await as('student');const thread=(await rpc('submit_content',{kind:'thread',title:'Question about revision',body:'How do you plan your revision?'})).value;const reply=(await rpc('submit_content',{kind:'reply',title:'Reply',body:'I use a calendar.',parent_id:thread.id})).value;await as('admin');await db.query("select public.review_content($1,'hidden')",[thread.id]);await as('anon');assert.equal((await db.query('select id from public.content where id in ($1,$2)',[thread.id,reply.id])).rows.length,0);await as('student');await assert.rejects(rpc('submit_content',{kind:'reply',title:'Reply',body:'Another reply',parent_id:thread.id}),/not available/);});
 await t.test('Posting restrictions are enforced by the database',async()=>{await as('owner');await db.query('select public.owner_ban_author($1,$2)',[post.id,'Repeated abuse']);await as('student');await assert.rejects(rpc('submit_content',{kind:'tip',title:'Another tip',body:'Trying to post'}),/Posting is disabled/);});
 await t.test('Owner can revoke an admin without exposing owner operations',async()=>{await as('owner');await db.query("select public.owner_set_admin('admin@example.test',false)");await as('admin');assert.equal((await scalar('select public.my_role() as role')).role,'student');await assert.rejects(db.query("select public.review_content($1,'hidden')",[post.id]),/Administrator access/);});
 await db.close();
});
